-- CreateTable
CREATE TABLE "budget" (
    "id" TEXT NOT NULL,
    "BUDGETEDCOUNTY" TEXT NOT NULL,
    "SETBUGET" INTEGER NOT NULL,
    "FINANCIALYEAR" TEXT NOT NULL,
    "createdat" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "budget_pkey" PRIMARY KEY ("id")
);
